# 应用名称
spring:
  profiles:
    # 添加其他的配置文件
    active: dataSource, resources
  # thymeleaf配置
  # 模板的模式，支持如：HTML、XML、TEXT、JAVASCRIPT等
  thymeleaf:
    mode: HTML5
    # 编码，可不用配置
    encoding: UTF-8
    # 内容类别，可不用配置
    servlet:
      content-type: text/html
    # 开发配置为false，避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认就是templates，可不用配置
    prefix:
      classpath: /templates/
  application:
    name: nots_web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
# 应用服务 WEB 访问端口
server:
  port: 9090
  servlet:
    context-path: /api
  max-http-header-size: 2MB