# 应用名称
spring:
  profiles:
    # 添加其他的配置文件
    active: dev, resources
  application:
    name: notes_web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
# 应用服务 WEB 访问端口
server:
  port: 9090
  servlet:
    context-path: /api
  max-http-header-size: 2MB