# 该配置文件用于配置项目变量值,便于维护

notes:
  qiNiuYun:
    accessKey: "nWy38ywpukJcuBChHj51Nh780xo6NnJsnY48ig-g"
    secretKey: "tZSTIwViHmoe4khSRDVX1Uqsa5l7VpU59Y6SXxNz"
    bucket: "mybebin-notes"
    domain: "http://ra6kdl6b6.hn-bkt.clouddn.com/"
    # todo：七牛云地址

