spring:
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/programme_Notes?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://120.24.48.80:3306/programme_notes?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.32.128:3306/programme_notes?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 数据库用户名&密码：
    username: root
    password: 333
  # redis配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
    redis:
      database: 0           # Redis服务器数据库
      host: 127.0.0.1       # Redis服务器地址
      port: 6379            # Redis服务器连接端口
      password: 123456      # Redis服务器连接密码（默认为空）
      timeout: 6000ms       # 连接超时时间（毫秒）
      jedis:
        pool:
          max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 0       # 连接池中的最小空闲连接

# 下面这些内容是为了让MyBatis映射
# 指定Mybatis的Mapper文件
mybatis_plus:
  mapper-locations: classpath:com/chen/notes_web/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl